// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import DialogController from "./dialog_controller";
application.register("dialog", DialogController);

import Dropdown from "@stimulus-components/dropdown";
application.register("dropdown", Dropdown);

import Notification from "@stimulus-components/notification";
application.register("flash", Notification);
